name: Deploy Cluster

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-central-1'
      # keypair:
      #   description: 'SSH Key Pair'
      #   required: true

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    # outputs:
    #   env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::291880462365:role/notejamdemo
        role-session-name: notejamuser-session

    # - name: Configure environment name
    #   id: env-name
    #   env:
    #     REPO: $GITHUB_REPOSITORY
    #   run: |
    #     ENVIRONMENT=`echo $REPO | tr "/" "-"`
    #     echo "Environment name: $ENVIRONMENT"
    #     echo "::set-output name=environment::$ENVIRONMENT"

    # - name: Deploy Entire Notejam Infrastructure
    #   id: notejamstack
    #   uses: aws-actions/aws-cloudformation-github-deploy@master
    #   with:
    #     name: ${{ steps.env-name.outputs.environment }}-cluster
    #     template: https://climatepartner.s3.eu-central-1.amazonaws.com/ClimatePartner/Integrated/noteJamMaster.yaml
    #     no-fail-on-empty-changeset: "1"
        # parameter-overrides: >-
        #   AvailabilityZones=${{ github.event.inputs.region }}a,
        #   AvailabilityZones=${{ github.event.inputs.region }}c,
        #   KeyPairName=${{ github.event.inputs.keypair }},
        #   NumberOfAZs=2,
        #   ProvisionBastionHost=Disabled,
        #   EKSPublicAccessEndpoint=Enabled,
        #   EKSPrivateAccessEndpoint=Enabled,
        #   RemoteAccessCIDR=0.0.0.0/0